[connections.gsheets]  # Fill all the empty xxx values from the JSON key file along with your private GSheets URL.
spreadsheet = "https://docs.google.com/spreadsheets/d/xxxxxxx/edit#gid=0"
worksheet = ""
type = "service_account"
project_id = "xxx"
private_key_id = "xxx"
private_key = "xxx"
client_email = "xxx"
client_id = "xxx"
auth_uri = https://accounts.google.com/o/oauth2/auth
token_uri = https://oauth2.googleapis.com/token

auth_provider_x509_cert_url = https://www.googleapis.com/oauth2/v1/certs
client_x509_cert_url = "xxx"
